In [1]:
import pandas as pd

# Define column names since they are not included in the dataset
column_names = [
    'age', 'workclass', 'fnlwgt', 'education', 'education-num', 'marital-status',
    'occupation', 'relationship', 'race', 'sex', 'hours-per-week', 'native-country', 'income'
]

# Load the dataset from the URL
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data"
adult_data = pd.read_csv(url, header=None, names=column_names, na_values=' ?', skipinitialspace=True)

# Display the first few rows of the dataset
print(adult_data.head())

# Check for missing values
missing_values = adult_data.isnull().sum()
print("\nMissing values in each column:\n", missing_values)

                        age  workclass  fnlwgt           education  \
39 State-gov          77516  Bachelors      13       Never-married
50 Self-emp-not-inc   83311  Bachelors      13  Married-civ-spouse
38 Private           215646    HS-grad       9            Divorced
53 Private           234721       11th       7  Married-civ-spouse
28 Private           338409  Bachelors      13  Married-civ-spouse

                         education-num marital-status occupation relationship  \
39 State-gov              Adm-clerical  Not-in-family      White         Male
50 Self-emp-not-inc    Exec-managerial        Husband      White         Male
38 Private           Handlers-cleaners  Not-in-family      White         Male
53 Private           Handlers-cleaners        Husband      Black         Male
28 Private              Prof-specialty           Wife      Black       Female

                     race  sex  hours-per-week native-country income
39 State-gov         2174    0              40  United-States  <=50K
50 Self-emp-not-inc     0    0              13  United-States  <=50K
38 Private              0    0              40  United-States  <=50K
53 Private              0    0              40  United-States  <=50K
28 Private              0    0              40           Cuba  <=50K

Missing values in each column:
 age               0
workclass         0
fnlwgt            0
education         0
education-num     0
marital-status    0
occupation        0
relationship      0
race              0
sex               0
hours-per-week    0
native-country    0
income            0
dtype: int64

In [2]:
import pandas as pd

# Define column names since they are not included in the dataset
column_names = [
    'age', 'workclass', 'fnlwgt', 'education', 'education-num', 'marital-status',
    'occupation', 'relationship', 'race', 'sex', 'hours-per-week', 'native-country', 'income'
]

# Load the dataset from the URL
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data"
adult_data = pd.read_csv(url, header=None, names=column_names, na_values=' ?', skipinitialspace=True)

# Display the first few rows of the dataset
print(adult_data.head())

# Check for missing values again
missing_values = adult_data.isnull().sum()
print("\nMissing values in each column:\n", missing_values)

                        age  workclass  fnlwgt           education  \
39 State-gov          77516  Bachelors      13       Never-married
50 Self-emp-not-inc   83311  Bachelors      13  Married-civ-spouse
38 Private           215646    HS-grad       9            Divorced
53 Private           234721       11th       7  Married-civ-spouse
28 Private           338409  Bachelors      13  Married-civ-spouse

                         education-num marital-status occupation relationship  \
39 State-gov              Adm-clerical  Not-in-family      White         Male
50 Self-emp-not-inc    Exec-managerial        Husband      White         Male
38 Private           Handlers-cleaners  Not-in-family      White         Male
53 Private           Handlers-cleaners        Husband      Black         Male
28 Private              Prof-specialty           Wife      Black       Female

                     race  sex  hours-per-week native-country income
39 State-gov         2174    0              40  United-States  <=50K
50 Self-emp-not-inc     0    0              13  United-States  <=50K
38 Private              0    0              40  United-States  <=50K
53 Private              0    0              40  United-States  <=50K
28 Private              0    0              40           Cuba  <=50K

Missing values in each column:
 age               0
workclass         0
fnlwgt            0
education         0
education-num     0
marital-status    0
occupation        0
relationship      0
race              0
sex               0
hours-per-week    0
native-country    0
income            0
dtype: int64

In [3]:
import pandas as pd

# Load the dataset from the URL
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
titanic_data = pd.read_csv(url)

# Display the first few rows of the dataset
print(titanic_data.head())

# Check for missing values
missing_values = titanic_data.isnull().sum()
print("\nMissing values in each column:\n", missing_values)

   PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                             Heikkinen, Miss. Laina  female  26.0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                           Allen, Mr. William Henry    male  35.0      0

   Parch            Ticket     Fare Cabin Embarked
0      0         A/5 21171   7.2500   NaN        S
1      0          PC 17599  71.2833   C85        C
2      0  STON/O2. 3101282   7.9250   NaN        S
3      0            113803  53.1000  C123        S
4      0            373450   8.0500   NaN        S

Missing values in each column:
 PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

 https://chatgpt.com/share/bd47c930-1e7f-443a-ab32-44706da3a5a2  s

---

**Summary:**

In our interaction, we explored various datasets available online and their handling of missing values. We began with the Netflix Movies and TV Shows dataset but encountered an issue with the link provided. We then explored the World Happiness Report dataset, which also had a problematic link. Finally, we successfully identified the UCI Adult Income Dataset but found it did not contain missing values.

To meet the requirements of the assignment, a suitable dataset with missing values was needed. We concluded with the Titanic dataset, which is known to contain missing values in various columns. I provided Python code using Pandas to load this dataset and check for missing values.

**Details of Provided Code:**

1. **Loading the Titanic Dataset:**
   ```python
   import pandas as pd

   # Load the dataset from the URL
   url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
   titanic_data = pd.read_csv(url)

   # Display the first few rows of the dataset
   print(titanic_data.head())
   ```

2. **Checking for Missing Values:**
   ```python
   # Check for missing values
   missing_values = titanic_data.isnull().sum()
   print("\nMissing values in each column:\n", missing_values)
   ```

This summary covers the datasets discussed, the issues encountered, and the final solution provided, including the code for handling missing values.

---